### ISSUE TITLE
libzfs depends

### ISSUE THREAD

**Issue by FransUrbo** [zfsonlinux/grub#8]
Build depends on <code>libzfs-dev</code> and depends on <code>libzfs</code>.

This doesn't fly when using debs from the ZoL repositories (which provides zfs-devel but not libzfs).

Solution (?):

Pre-depends: libzfs-dev | zfs-devel

**Comment by behlendorf** [comment]
I'm not sure exactly how dependencies work for debs.  But with rpms you can list the package or a file provided by the package.  So maybe it makes sense to have this depend on the libzfs.so library rather than the package name.  Someone would need to test this.

**Comment by FransUrbo** [comment]
A deb does not provide every lib that it contains. The dependency is 'hardcoded' into the package (can be in a dynamical way in the debian/control file and figured out when creating the binary package).

So grub needs to depend on either <code>libzfs</code> (which it does today) OR <code>zfs</code> which is the package that contains the libzfs library when building from the ZoL repository.

It's either that, or the <code>zfs</code> resulting package should provide <code>libzfs</code>. I find that more difficult to do, since we're using alien to create the deb from the rpm...

Personally, I think the former should be done - the grub depends should be fixed, not zfs providing libzfs...

I'm currently working on seeing if this could be solved in a good way. @dajhorn, is this also a problem in the Ubuntu packages?

**Comment by dajhorn** [comment]
@FransUrbo, what problem does this proposal solve?

Accommodating alien dependencies has expensive side effects.  For example, too many people already mixmatch packaged binaries with local builds, and this proposal will make that kind of user mistake easier.

Regarding GRUB on Ubuntu, an explicit versioned dependency will be required for a sane upgrade to the pending ZoL 0.6.3 tag.  Specifically,  `dpkg-shlibdeps` does not recognize the partial soname revision that came with the libzfs_core import.  This is what @danielkza was actually reporting in https://github.com/zfsonlinux/pkg-zfs/issues/104#issuecomment-35922048.

Plus, I'm pretty sure that pkg-zfs used zfs-devel until the first downstream Debian code review happened.  Chapter 8 of the policy manual stipulates a library package naming convention, and pkg-zfs conforms.

**Comment by danielkza** [comment]
Sorry if I'm missing some previous discussion, not being a developer for the project, but:

a) What is the reasoning for going with alien over 'native' debian packaging?
b) Does libzfs absolutely need to be bundled with the zfs package? It seems it isn't actually a 'private' library if there are other clients relying on it like GRUB, so packaging it separately seems like a good idea, even for the RPM dist.

**Comment by FransUrbo** [comment]
> a) What is the reasoning for going with alien over 'native' debian packaging?
> 
> See https://github.com/zfsonlinux/zfs/pull/1713
> b) Does libzfs absolutely need to be bundled with the zfs package? It seems it isn't actually a 'private' library if there are other clients relying on it like GRUB, so packaging it separately seems like a good idea, even for the RPM dist.
> 
> I agree. @behlendorf?

**Comment by dajhorn** [comment]
> a) What is the reasoning for going with alien over 'native' debian packaging?

If you manually download the latest ZoL source code and run `make deb`, then you get RPM packages that have been converted to DEB packages.

These alien packages sorta kinda mostly work the same as the native packages that are published at the PPA for Ubuntu systems, or the native packages that are stuck in review limbo at debian.org downstream.

> b) Does libzfs absolutely need to be bundled with the zfs package?

The native libzfs package built from the pkg-zfs overlay can be installed without the zfs package.

**Comment by FransUrbo** [comment]
> @FransUrbo, what problem does this proposal solve?
> 
> It makes grub installable, even if one uses the debs built from the ZoL repository (and not pkg-zfs).
> Regarding GRUB on Ubuntu, an explicit versioned dependency will be required for a sane upgrade to the pending ZoL 0.6.3 tag.
> 
> Does it?! See https://github.com/zfsonlinux/zfs/issues/1820#issuecomment-35938733

**Comment by dajhorn** [comment]
> Does it?!

Yes, it does indeed.  I noticed a glitch in coverage testing and reported it to @behlendorf  last November 8th.  The change carries a small risk of breaking business systems and appliances that put proprietary code on top of libzfs, but the fix is easy and it won't surprise anybody that actually tests their work.

**Comment by FransUrbo** [comment]
Got a proper bug report you can direct me to?

**Comment by dajhorn** [comment]
> Got a proper bug report you can direct me to?

No, it isn't an outstanding bug, so wait for the code to be tested and published.  In the meantime, build a demo for your proposal.

**Comment by FransUrbo** [comment]
My plan was to

```
Build-Depends: ....., libzfs-dev | zfs-devel [linux-any]
[...]
Package: {grub-common,grub-emu,grub-pc-bin}
Depends: libzfs | zfs, .....
```

And in <code>debian/rules</code>:

```
-       dh_shlibdeps -X.module
+       dh_shlibdeps -X.module -- -xzfs
```

That way, it will ignore the libzfs/zfs dependency (depending on where it finds <code>/lib/libzfs.so.2</code>) and instead use the hardcoded one above. But if indeed we need/require a versioned dependency, that won't work. I'll see what I can figure out instead...

**Comment by danielkza** [comment]
> If you manually download the latest ZoL source code and run make deb, then you get RPM packages that have been converted to DEB packages.
> 
> These alien packages sorta kinda mostly work the same as the native packages that are published at the PPA for Ubuntu systems, or the native packages that are stuck in review limbo at debian.org downstream.

I understand, and I've had success using them to get a recent build with some small adaptations, but I was curious _why_ it was done this way.

If I may pose a suggestion, like I did to @FransUrbo before, the Debian packaging resources could be stored in a separate branch so as not to pollute the main source tarball as used by other distributions. Debian's git-buildpackage is capable of fetching the sources and build instructions from separate branches.

Always having the ability to build current Debian packages would be very helpful to people trying to test and report bugs, and make releases much less painful by dealing with issues continually instead of all at once.

> The native libzfs package built from the pkg-zfs overlay can be installed without the zfs package.

Only coincidentally since they're shipping different versions now, but whenever 0.6.3 is released with libzfs2 they will overwrite files from each other. What would be the disadvantages of having a separate libzfs package?

**Comment by dajhorn** [comment]
> If I may pose a suggestion, like I did to @FransUrbo before, the Debian packaging resources could be stored in a separate branch so as not to pollute the main source tarball as used by other distributions. Debian's git-buildpackage is capable of fetching the sources and build instructions from separate branches.

Three things:

First, the zfsonlinux/pkg-zfs repository is expressly intended for this purpose, and all release builds for Ubuntu already happen through `git-buildpackage`.  Notice the `debian/gbp.conf` file in each target branch.  These overlays are not in zfsonlinux/zfs itself so that the packaging team can have write privileges to a repository in the Github organization account.

The workflow is described here:
- https://groups.google.com/a/zfsonlinux.org/d/msg/zfs-discuss/BlZhmzh-2L0/c0MGB-nV3WwJ

Second, some of the snapshot/ branches are mangled because there are changes between 0.6.2 and HEAD that cannot be represented in a debdiff, which breaks `git-buildpackage --snapshot` automation, and also breaks publishing to Launchpad.  The kludges in the snapshot/ branches must be carried until a new upstream release tarball is available.

Third, the branches for Debian are disjoint from upstream, which breaks `git-buildpackage` tag management.  Consequently, the source code for Debian published to Github does not reproducibly match the binaries that are published to the http://archive.zfsonlinux.org site.

> Only coincidentally since they're shipping different versions now, but whenever 0.6.3 is released with libzfs2 they will overwrite files from each other. What would be the disadvantages of having a separate libzfs package?

Hence the versioned dependency that I mentioned earlier.  On DEB systems, only local installations should be affected by this issue.  Whether to unroll libzfs for RPM builds, including alien `make deb` builds, is a decision for the people that are working on the RHEL platforms.

**Comment by danielkza** [comment]
Thank you for elaborating. I have some further questions, but be free to tell me to bugger off if I'm being too annoying.
- The packaging team is trusted to have their releases distributed officially, but not to commit to the main repository? I'm not sure I understand how the teams are separated.
- Integrating Debian packaging in the main repo was AFAIK rejected due to tree pollution, but the RPM infrastructure is accepted. I can only assume that is due to the main team only wanting/being able to maintain RPM builds by themselves, but apparently you @dajhorn and @FransUrbo have enough time to do the same for Debian, so I can't understand the reasoning for the rejection.
- The issue with the tarball diffs seems really unfortunate. I don't have a huge amount of experience with it, but I never had problems generating pristine tars before. Do you know what in particular caused the breakage? Can a clean rebase after 0.6.3 fix everything, and is it possible to avoid it in the future?

> Hence the versioned dependency that I mentioned earlier. On DEB systems, only local installations should be affected by this issue.

Unfortunately that's currently my only alternative for getting recent builds for testing. I got a mostly working merge of the mainstream tree into pkg-zfs, but it has been a major pain in the ass, which will likely repeat itself on future releases without some form of continuous integration. I'll send a pull request shortly if you want to check it out (will likely be a long diff with the multiple merges).

> Whether to unroll libzfs for RPM builds, including alien make deb builds, is a decision for the people that are working on the RHEL platforms.

Absolutely, but I believe separation would be the right decision either way, considering libzfs is showing itself not to be a private library. I'm actually looking into using libzfs_core for a project, and while I could easily depend on the soname for RPM, Debian offers no such possiblity, and it is my main target ecosystem.

**Comment by dajhorn** [comment]
> The packaging team is trusted to have their releases distributed officially, but not to commit to the main repository? I'm not sure I understand how the teams are separated.

Right.  @behlendorf personally tests and signs-off on the primary repository.

> so I can't understand the reasoning for the rejection

There is a large amount of history in the tracker and lists on this topic.  Debian also asks that upstream products do not bundle an overlay.

> Do you know what in particular caused the breakage?

In this case, I think it was a mode change.  Previously, it has been things like autotools products and git ignore lists.  If you revert the standards demotion commit and try to rebuild, then you'll get a lintian warning and a gbp failure that describes the problem.

> I'll send a pull request shortly if you want to check it out (will likely be a long diff with the multiple merges).

Certainly.  Note that I will be refreshing the daily builds when the Trusty beta release happens this week, so you may want wait a few days.

**Comment by FransUrbo** [comment]
> The packaging team is trusted to have their releases distributed officially, but not to commit to the main repository?
> 
> No, we're allowed to do both.

But we (the release team - me and @dajhorn currently) only have write access to the pkg-\* repository
(and grub, but that's another thing), not to the main repo. Only (that I know of) @behlendorf have
access to that.

> Integrating Debian packaging in the main repo was AFAIK rejected due to tree pollution
> 
> Correct.
> but the RPM infrastructure is accepted.
> 
> Correct again. A little unfair if you ask me - the official Debian GNU/Linux maintainer for ZoL, Aron
> Xu, have shown interest in having the debian directory upstream (as in ZoL). But I didn't believe in the
> fight enough to go ten rounds with it :)
> but apparently you @dajhorn and @FransUrbo have enough time to do the same for Debian
> 
> Yes (for me any way). I contribute quite a lot anyway, and is the maintainer for the SMB and iSCSI
> part in ZoL anyway. And some other small bits and pieces that isn't part of the actually filesystem.
> Unfortunately that's currently my only alternative for getting recent builds to test.
> 
> As soon as S3/AWS have synced, you'll be able to do an upgrade to the very latest git HEAD
> doing the normal procedure - I've got the basis of a daily-snapshots working for Debian GNU/Linux
> working (@dajhorn is doing this for Ubuntu). For now it's manual, but I'll write some scripts and do it in 
> a more automated fashion later :)

I'll announce it to the list within the hour (hopefully).

> I'll send a pull request shortly if you want to check it out
> 
> Turns out I got some time over (got stuck with my iSCSI patch modifications), so I did it myself :). But
> thanx for reporting on progress!

**Comment by danielkza** [comment]
Thank you all for taking the time to respond, and sorry for taking much of your time.

@FransUrbo Do you still want me to send the pull request to compare anything or is it not necessary? Either way I'll be waiting to test out your builds whenever you get them out. I have to confess I have a vested interest in getting 0.6.3 rolling on Debian so I can deploy kernel 3.12 in a production system in a couple of months :)

**Comment by FransUrbo** [comment]
> @FransUrbo Do you still want me to send the pull request to compare anything or is it not necessary?
> 
> By all means do. You'll never know what I've missed :). I've tested an upgrade to the new version
> on a clean install, but that don't necessarily mean that much :).
> I have to confess I have a vested interest in getting 0.6.3 rolling on Debian
> 
> I had to upgrade to 3.12.0 when it was released quite a while ago to have my SATA/SAS cards
> working in tandem (the driver <3.9 only worked with one of the cards, 3.9 worked 'most of the time',
> but 3.12 had some substantial rewrites to the code that made both work all the time without any
> problems). But I run from the ZoL repo.... Easier - I get both the userland and the module at the same
> time without going through dkms...

**Comment by FransUrbo** [comment]
It seems like the symlink solution mentioned in https://github.com/zfsonlinux/zfs/issues/1820#issuecomment-35938733 works just fine:

```
debian:/lib# ldd /usr/sbin/grub-mkdevicemap | grep libzfs
        libzfs.so.1 => /lib/libzfs.so.1 (0x00007fb7c0481000)
        libzfs_core.so.1 => /lib/libzfs_core.so.1 (0x00007fb7bf693000)
debian:/lib# ll /lib/libzfs.so.1
lrwxrwxrwx 1 root root 11 Feb 25 08:38 /lib/libzfs.so.1 -> libzfs.so.2
debian:/lib# ll /lib/libzfs.so.2
lrwxrwxrwx 1 root root 15 Feb 25 08:30 /lib/libzfs.so.2 -> libzfs.so.2.0.0
debian:/lib# ll /lib/libzfs.so.2.0.0 
-rw-r--r-- 1 root root 281224 Feb 25 08:30 /lib/libzfs.so.2.0.0
```

**Comment by FransUrbo** [comment]
Versioned depend on libzfs|zfs have been introduced in tag 'master/debian/wheezy/2.00-22debian1+zfs3+0.6.3-1_wheezy' and uploaded to the wheezy-daily repository.

**Comment by behlendorf** [comment]
Let me touch on a few things.

> Right. @behlendorf personally tests and signs-off on the primary repository.

One of the reasons I personally sign off on everything is to make sure it all receives the proper testing.  Unfortunately, right now the full test infrastructure isn't setup to be public.  All the tests cases are available but they are a bit complicated to run.  Ideally I'd like any one who opens a pull request to be able to see the full testing results from their proposed changed but we're not their yet.

As for versioned libzfs packages that certainly looks like the right thing to do.  Originally, I didn't split the library in to it's own package but after reading the Fedora / RHEL / SuSE / Debian packaging guidelines it certainly looks like I should have.  I'll look in to doing this for the next tag and I'd love to get your guys feedback to make sure I've done it correctly and don't accidentally cause any trouble for your packages.
